### ISSUE TITLE
AI Wont Follow Path #2

### ISSUE THREAD

**Issue by PlayPrey** [PlayPrey/SPraceMod#3]
I don't know whats causing this, the AI follows other tasks in the sequence but the DriveTo ones.

**Comment by flynhigh09** [comment]
got ai to drive but added a ped n it doesnt get in vehicle, then other driver stops after firts checkpoint think.

**Comment by PlayPrey** [comment]
Fixed issue; I had mistaken radius for destination with the speed.

flynight09; Are you using task sequences?
